name: Docker CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Docker Push
        uses: warchant/Publish-Docker-Github-Action@3
        with:
          name: veriblock/vbtc-cpuminer
          dockerfile: Dockerfile
          username: ${{ secrets.PUBLIC_DOCKERHUB_USERNAME }}
          password: ${{ secrets.PUBLIC_DOCKERHUB_PASSWORD }}
          snapshot: true